name: Video Call App with React Native & webRTC

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint and Prettier
        run: npm run lint # Assuming you have a lint script in your package.json
